name: Lighthouse Audit
on: [pull_request]

env:
  PR_URL: https://deploy-preview-${{github.event.number}}--hacknitr.netlify.app/?utm_source=github&utm_campaign=bot_dp
  
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: /tmp/artifacts
          urls:$PR_URL
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
